initial_step: 50
candidates_to_seed: 1000
candidates_per_step: 5
predictor_objective: MAE
acquisition_function: ITS
predictor_ensembles: 5
predictor_iters: 723
max_path_length: 4
predictor_lr: 0.012197
candidate_generation: 
    type: mutation
    top_part: 0.25
    probas:
        reconnect: 0.25
        add: 0.25
        delete: 0.25
        change_op: 0.25
    
train_epochs: 20
scoring_metric: auc