gender:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro", "auc"]
    epochs: 100
    scoring_metric: "auc"
    lr: 0.001
    weight_decay: 0.0001
  dataset:
    data_path: "/home/dev/data_main/NAS/gender/processed.csv" 
    batch_size:  64
    min_len:  150
    seq_len:  350
    TARGET:  "gender"
    categorical:  ["mcc_code", "tr_type", "time_period", "neg_amount", "is_big"]
    continious:  ["amount_round", "day_diff"]
    main_index: "customer_id"
    val_portion: 0.3
    time_index: "tr_datetime"
  model:
    hidden_size: 128 
    output_size: 2
    embeddings_hidden: 128
    

raif:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro","auc"]
    epochs: 100
    scoring_metric: "auc"
    lr: 0.0001
    weight_decay: 0.0001
  dataset:
    data_path: '/home/dev/data_main/NAS/raifhack/transactions_joint.csv'
    batch_size:  32
    min_len:  150
    seq_len:  200
    TARGET:  "gender"
    categorical:  ["mcc"]
    continious:  ["amount"]
    main_index: "cnum"
    val_portion: 0.3
    time_index: "new_date"
  model:
    hidden_size: 128 
    output_size: 2
    embeddings_hidden: 128


age:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro"]
    epochs: 40
    scoring_metric: "accuracy"
    lr: 0.0001
    weight_decay: 0.00001
  dataset:
    data_path: "/home/dev/data_main/NAS/age/age_clear.csv"
    batch_size:  64
    min_len:  250
    seq_len:  450
    TARGET:  "bins"
    categorical:  ["small_group"]
    continious:  ["amount_rur"]
    main_index: "client_id"
    val_portion: 0.3
    time_index: "trans_date"
  model:
    hidden_size: 128
    output_size: 4
    embeddings_hidden: 128

elo:
  trainer:
    loss: "MSELoss"
    metrics: ["rmse", "r2"]
    epochs: 40
    scoring_metric: "rmse"
    lr: 0.001
    weight_decay: 0.0001
  dataset:
    data_path: "/home/dev/data_main/NAS/elo/elo_clear.csv"
    batch_size:  32
    min_len:  100
    seq_len:  350
    TARGET:  "target"
    categorical:  ['authorized_flag', 'category_1', 'installments',
       'category_3', 'category_2', 'state_id', 'subsector_id',
       'most_recent_sales_range', 'most_recent_purchases_range',
       'category_4', 'merchant_category_2', 'merchant_category_1',
       'first_active_month', 'feature_1', 'feature_2', 'feature_3']
    continious:  ['purchase_amount', 'month_lag', 'numerical_1', 'numerical_2', 
                    'avg_sales_lag3', 'active_months_lag3', 'avg_sales_lag6', 
                    'active_months_lag6', 'avg_sales_lag12', 'active_months_lag12']
    main_index: "card_id"
    val_portion: 0.3
    time_index: "purchase_date"
  model:
    hidden_size: 64
    output_size: 1
    embeddings_hidden: 16

insect:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro"]
    epochs: 100
    scoring_metric: "accuracy"
    lr: 0.0001
    weight_decay: 0.0001
  dataset:
    data_path: "/home/dev/data_main/NAS/insect/insect_clear.csv"
    batch_size: 64
    min_len:  100
    seq_len:  200
    TARGET:  "target"
    categorical:  []
    continious:  ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22']
    main_index: "id"
    val_portion: 0.3
    time_index: "time"
  model:
    hidden_size: 64
    output_size: 10
    embeddings_hidden: 128
    
emo_big:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro","f1_weighted"]
    epochs: 100
    scoring_metric: "f1_weighted"
    lr: 0.001
    weight_decay: 0.00001
  dataset:
    data_path: "/home/dev/data_main/NAS/SPEECH/big_set.json"
    batch_size:  32
    min_len:  32000
    seq_len:  64000
    TARGET:  "emotion"
    categorical:  []
    continious:  []
    main_index: ""
    val_portion: 0.2
    time_index: ""
  model:
    hidden_size: 512
    output_size: 7 
    embeddings_hidden: ''




emovo:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro","f1_weighted"]
    epochs: 100
    scoring_metric: "f1_weighted"
    lr: 0.001
    weight_decay: 0.00001
  dataset:
    data_path: "/home/dev/data_main/NAS/SPEECH/emovo.json"
    batch_size:  32
    min_len:  32000
    seq_len:  64000
    TARGET:  "speaker" # emotion  speaker gender
    categorical:  []
    continious:  []
    main_index: ""
    val_portion: 0.2
    time_index: ""
  model:
    hidden_size: 512
    output_size: 6 # 7 for emotion / 6 for speaker / 2 for gender
    embeddings_hidden: ''



emotions:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro","f1_weighted"]
    epochs: 100
    scoring_metric: "f1_weighted"
    lr: 0.001
    weight_decay: 0.00001
  dataset:
    data_path: "/home/dev/data_main/NAS/SPEECH/emotions.json"
    batch_size:  32
    min_len:  32000
    seq_len:  64000
    TARGET:  "emotion" # emotion  speaker gender
    categorical:  []
    continious:  []
    main_index: ""
    val_portion: 0.2
    time_index: ""
  model:
    hidden_size: 512
    output_size: 7 
    embeddings_hidden: ''


medproblem:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro","f1_weighted"]
    epochs: 50
    scoring_metric: "f1_weighted"
    lr: 0.001
    weight_decay: 0.00001
  dataset:
    data_path: "/home/dev/data_main/NAS/medproblem/annotations.json"
    batch_size:  32
    min_len:  32000
    seq_len:  62000
    TARGET:  "prompt" 
    categorical:  []
    continious:  []
    main_index: ""
    val_portion: 0.2
    time_index: ""
  model:
    hidden_size: 128
    output_size: 25 
    embeddings_hidden: ''

friends:
  trainer:
    loss: "CrossEntropyLoss"
    metrics: ["accuracy", "f1_macro","f1_weighted"]
    epochs: 100
    scoring_metric: "f1_weighted"
    lr: 0.001
    weight_decay: 0.0001
  dataset:
    data_path: "/home/dev/data_main/NAS/SPEECH/friends.json"
    batch_size:  16
    min_len:  32000
    seq_len:  64000
    TARGET:  "emotion" # emotion  sentiment
    categorical:  []
    continious:  []
    main_index: ""
    val_portion: 0.1
    time_index: ""
  model:
    hidden_size: 64 
    output_size: 7 # 3 for sentiment / 7 for emotion
    embeddings_hidden: ''


big_regression:
  trainer:
    loss: "MSELoss"
    metrics: ["rmse", "r2"]
    epochs: 25
    scoring_metric: "rmse"
    lr: 0.001
    weight_decay: 0.00001
  dataset:
    data_path: "/home/dev/data_main/NAS/big_regression/train.csv"
    batch_size: 64
    min_len:  900
    seq_len:  1200
    TARGET:  "target"
    categorical:  []
    continious:  ['f_0', 'f_1', 'f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10', 
                'f_11', 'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17', 'f_18', 'f_19', 'f_20', 
                'f_21', 'f_22', 'f_23', 'f_24', 'f_25', 'f_26', 'f_27', 'f_28', 'f_29', 'f_30', 
                'f_31', 'f_32', 'f_33', 'f_34', 'f_35', 'f_36', 'f_37', 'f_38', 'f_39', 'f_40', 
                'f_41', 'f_42', 'f_43', 'f_44', 'f_45', 'f_46', 'f_47', 'f_48', 'f_49', 'f_50', 
                'f_51', 'f_52', 'f_53', 'f_54', 'f_55', 'f_56', 'f_57', 'f_58', 'f_59', 'f_60',
                'f_61', 'f_62', 'f_63', 'f_64', 'f_65', 'f_66', 'f_67', 'f_68', 'f_69', 'f_70',
                'f_71', 'f_72', 'f_73', 'f_74', 'f_75', 'f_76', 'f_77', 'f_78', 'f_79', 'f_80', 
                'f_81', 'f_82', 'f_83', 'f_84', 'f_85', 'f_86', 'f_87', 'f_88', 'f_89', 'f_90', 
                'f_91', 'f_92', 'f_93', 'f_94', 'f_95', 'f_96', 'f_97', 'f_98', 'f_99', 'f_100', 
                'f_101', 'f_102', 'f_103', 'f_104', 'f_105', 'f_106', 'f_107', 'f_108', 'f_109', 
                'f_110', 'f_111', 'f_112', 'f_113', 'f_114', 'f_115', 'f_116', 'f_117', 'f_118', 
                'f_119', 'f_120', 'f_121', 'f_122', 'f_123', 'f_124', 'f_125', 'f_126', 'f_127', 
                'f_128', 'f_129', 'f_130', 'f_131', 'f_132', 'f_133', 'f_134', 'f_135', 'f_136', 
                'f_137', 'f_138', 'f_139', 'f_140', 'f_141', 'f_142', 'f_143', 'f_144', 'f_145', 
                'f_146', 'f_147', 'f_148', 'f_149', 'f_150', 'f_151', 'f_152', 'f_153', 'f_154', 
                'f_155', 'f_156', 'f_157', 'f_158', 'f_159', 'f_160', 'f_161', 'f_162', 'f_163', 
                'f_164', 'f_165', 'f_166', 'f_167', 'f_168', 'f_169', 'f_170', 'f_171', 'f_172', 
                'f_173', 'f_174', 'f_175', 'f_176', 'f_177', 'f_178', 'f_179', 'f_180', 'f_181', 
                'f_182', 'f_183', 'f_184', 'f_185', 'f_186', 'f_187', 'f_188', 'f_189', 'f_190', 
                'f_191', 'f_192', 'f_193', 'f_194', 'f_195', 'f_196', 'f_197', 'f_198', 'f_199', 
                'f_200', 'f_201', 'f_202', 'f_203', 'f_204', 'f_205', 'f_206', 'f_207', 'f_208', 
                'f_209', 'f_210', 'f_211', 'f_212', 'f_213', 'f_214', 'f_215', 'f_216', 'f_217', 
                'f_218', 'f_219', 'f_220', 'f_221', 'f_222', 'f_223', 'f_224', 'f_225', 'f_226', 
                'f_227', 'f_228', 'f_229', 'f_230', 'f_231', 'f_232', 'f_233', 'f_234', 'f_235', 
                'f_236', 'f_237', 'f_238', 'f_239', 'f_240', 'f_241', 'f_242', 'f_243', 'f_244', 
                'f_245', 'f_246', 'f_247', 'f_248', 'f_249', 'f_250', 'f_251', 'f_252', 'f_253', 
                'f_254', 'f_255', 'f_256', 'f_257', 'f_258', 'f_259', 'f_260', 'f_261', 'f_262', 
                'f_263', 'f_264', 'f_265', 'f_266', 'f_267', 'f_268', 'f_269', 'f_270', 'f_271', 
                'f_272', 'f_273', 'f_274', 'f_275', 'f_276', 'f_277', 'f_278', 'f_279', 'f_280', 
                'f_281', 'f_282', 'f_283', 'f_284', 'f_285', 'f_286', 'f_287', 'f_288', 'f_289', 
                'f_290', 'f_291', 'f_292', 'f_293', 'f_294', 'f_295', 'f_296', 'f_297', 'f_298', 'f_299']
    main_index: "investment_id"
    val_portion: 0.3
    time_index: "time_id"
    seq2seq: True
  model:
    hidden_size: 128
    output_size: 1
    embeddings_hidden: 8